name: Feature
description: Describe a feature you would like to see
title: "[REQ] "
labels: [ feature request ]
body:
  - type: textarea
    id: description
    attributes:
      label: Feature
      description: Describe the feature as precise as possible.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Provide links or screenshots to further illustrate your idea.
    validations:
      required: false
